!function(a){var b=function(b){this.element=a(b)};b.prototype={constructor:b,show:function(){var b=this.element,g=b.closest("ul:not(.dropdown-menu)"),d=b.attr("data-target"),e;d||(d=(d=b.attr("href"))&&d.replace(/.*(?=#[^\s]*$)/,""));b.parent("li").hasClass("active")||(e=g.find(".active a").last()[0],b.trigger({type:"show",relatedTarget:e}),d=a(d),this.activate(b.parent("li"),g),this.activate(d,d.parent(),function(){b.trigger({type:"shown",relatedTarget:e})}))},activate:function(b,g,d){function e(){h.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");
b.addClass("active");k?(b[0].offsetWidth,b.addClass("in")):b.removeClass("fade");b.parent(".dropdown-menu")&&b.closest("li.dropdown").addClass("active");d&&d()}var h=g.find("> .active"),k=d&&a.support.transition&&h.hasClass("fade");k?h.one(a.support.transition.end,e):e();h.removeClass("in")}};a.fn.tab=function(c){return this.each(function(){var g=a(this),d=g.data("tab");d||g.data("tab",d=new b(this));if("string"==typeof c)d[c]()})};a.fn.tab.Constructor=b;a(function(){a("body").on("click.tab.data-api",
'[data-toggle="tab"], [data-toggle="pill"]',function(b){b.preventDefault();a(this).tab("show")})})}(window.jQuery);
(function(){var a=jQuery;a.fn.emulateTransitionEnd=function(b){var c=!1,g=this;a(this).one(a.support.transition.end,function(){c=!0});setTimeout(function(){c||a(g).trigger(a.support.transition.end)},b);return this};a(function(){var b=a.support,c;a:{c=document.createElement("bootstrap");var g={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},d;for(d in g)if(void 0!==c.style[d]){c={end:g[d]};break a}c=void 0}b.transition=
c});NaN})();
(function(a){a.fn.hovercard=function(b){b=a.extend({openOnLeft:!1,openOnTop:!1,cardImgSrc:"",detailsHTML:"",showCustomCard:!1,customCardJSON:{},customDataUrl:"",delay:0,autoAdjust:!0,onHoverIn:function(){},onHoverOut:function(){}},b);return this.each(function(){function c(a){var d=a.find(".hc-details").eq(0),c=a[0].getBoundingClientRect(),a=c.left+335+d.width(),c=c.top+335+d.height();b.openOnLeft||b.autoAdjust&&a>window.innerWidth?d.addClass("hc-details-open-left"):d.removeClass("hc-details-open-left");b.openOnTop||
b.autoAdjust&&c>window.innerHeight?d.addClass("hc-details-open-top"):d.removeClass("hc-details-open-top")}var g=a(this);g.wrap('<div class="hc-preview" />');g.addClass("hc-name");var d="";0<b.cardImgSrc.length&&(d='<img class="hc-pic" src="'+b.cardImgSrc+'" />');g.after('<div class="hc-details" >'+d+b.detailsHTML+"</div>");g.siblings(".hc-details").eq(0).css({width:b.width,background:b.background});g.closest(".hc-preview").hover(function(){var d=a(this);c(d);d.css("zIndex","200");g.css("zIndex","100").find(".hc-details").css("zIndex",
"50");var h=d.find(".hc-details").eq(0);h.stop(!0,!0).delay(b.delay).fadeIn();if("function"==typeof b.onHoverIn){if(b.showCustomCard&&0>=h.find(".s-card").length){var k=b.customDataUrl;"undefined"!=typeof g.attr("data-hovercard")&&0<g.attr("data-hovercard").length&&(k=g.attr("data-hovercard"));var d=b.customCardJSON,l,m;l=function(a){return'<div class="s-card s-card-pad">'+(a.image?'<img class="s-img" src='+a.image+" />":"")+(a.name?'<label class="s-name">'+a.name+" </label><br/>":"")+(a.link?'<a class="s-loc" href="'+
a.link+'">'+a.link+"</a><br/>":"")+(a.bio?'<p class="s-desc">'+a.bio+"</p>":"")+(a.website?'<p class="s-desc"><span class="s-strong">Web:</span><br/><a href="'+a.website+'">'+a.website+"</a></p>":"")+(a.email?'<p class="s-desc"><span class="s-strong">Email:</span><br/><a href="'+a.email+'">'+a.email+"</a></p>":"")+"</div>"};m=function(){};a.isEmptyObject(d)&&!h.hasClass("busy-loading")?(h.addClass("busy-loading"),a.ajax({url:k,type:"GET",dataType:"jsonp",timeout:4E3,beforeSend:function(){h.find(".s-message").remove();
h.append('<p class="s-message">Loading...</p>')},success:function(a){0>=a.length?h.find(".s-message").html("Sorry, no data found."):(h.find(".s-message").remove(),h.prepend(l(a)),c(h.closest(".hc-preview")),h.stop(!0,!0).delay(b.delay).fadeIn(),m(a));h.removeClass("busy-loading")},error:function(){h.find(".s-message").html("Sorry, no data found.");h.removeClass("busy-loading")}})):h.prepend(l(d))}b.onHoverIn.call(this)}},function(){$this=a(this);$this.find(".hc-details").eq(0).stop(!0,!0).fadeOut(300,
function(){$this.css("zIndex","0");g.css("zIndex","0").find(".hc-details").css("zIndex","0");"function"==typeof b.onHoverOut&&b.onHoverOut.call(this)})})})}})(jQuery);
(function(a){a.isScrollToFixed=function(b){return void 0!==a(b).data("ScrollToFixed")};a.ScrollToFixed=function(b,c){function g(){var a=i.options.limit;return!a?0:"function"===typeof a?a():a}function d(){return"fixed"===p}function e(){return"absolute"===p}function h(){d()||(q.css({display:f.css("display"),width:f.outerWidth(!0),height:f.outerHeight(!0),"float":f.css("float")}),f.css({width:f.width(),position:"fixed",top:-1==i.options.bottom?i.options.marginTop:"",bottom:-1==i.options.bottom?"":i.options.bottom}),
p="fixed")}function k(){if(d()||e())u=-1,q.css("display","none"),f.css({width:"",position:"",left:"",top:""}),p=null}function l(a){a!=u&&(f.css("left",r-a),u=a)}function m(){if(a.isScrollToFixed(f)){var b=v;v||(f.trigger("preUnfixed"),k(),f.trigger("unfixed"),u=-1,z=f.offset().top,r=f.offset().left,i.options.offsets&&(r+=f.offset().left-f.position().left),-1==j&&(j=r),p=f.css("position"),v=!0,-1!=i.options.bottom&&(f.trigger("preFixed"),h(),f.trigger("fixed")));var c=a(window).scrollLeft(),q=a(window).scrollTop(),
m=g();if(i.options.minWidth&&a(window).width()<i.options.minWidth){if(d()||e()||!b)t(),f.trigger("preUnfixed"),k(),f.trigger("unfixed")}else if(-1==i.options.bottom)if(0<m&&q>=m-i.options.marginTop){if(!e()||!b)t(),f.trigger("preAbsolute"),f.css({width:f.width(),position:"absolute",top:g(),left:r}),p="absolute",f.trigger("unfixed")}else if(q>=z-i.options.marginTop){if(!d()||!b)t(),f.trigger("preFixed"),h(),u=-1,f.trigger("fixed");l(c)}else{if(d()||e()||!b)t(),f.trigger("preUnfixed"),k(),f.trigger("unfixed")}else 0<
m?q+a(window).height()-f.outerHeight(!0)>=m-i.options.marginTop?d()&&(t(),f.trigger("preUnfixed"),k(),f.trigger("unfixed")):(d()||(t(),f.trigger("preFixed"),h()),l(c),f.trigger("fixed")):l(c)}}function t(){var a=f.css("position");"absolute"==a?f.trigger("postAbsolute"):"fixed"==a?f.trigger("postFixed"):f.trigger("postUnfixed")}var i=this;i.$el=a(b);i.el=b;i.$el.data("ScrollToFixed",i);var v=!1,f=i.$el,p,z=0,r=0,j=-1,u=-1,q=null,w=function(){f.is(":visible")&&(v=!1,m())},A=function(){m()};i.init=function(){i.options=
a.extend({},a.ScrollToFixed.defaultOptions,c);if(!("iPad"===navigator.platform||"iPhone"===navigator.platform||"iPod"===navigator.platform)||navigator.userAgent.match(/OS 5_.*\ like Mac OS X/i))i.$el.css("z-index",i.options.zIndex),q=a("<div />"),p=f.css("position"),!d()&&!e()&&i.$el.after(q),a(window).bind("resize.ScrollToFixed",w),a(window).bind("scroll.ScrollToFixed",A),i.options.preFixed&&f.bind("preFixed.ScrollToFixed",i.options.preFixed),i.options.postFixed&&f.bind("postFixed.ScrollToFixed",
i.options.postFixed),i.options.preUnfixed&&f.bind("preUnfixed.ScrollToFixed",i.options.preUnfixed),i.options.postUnfixed&&f.bind("postUnfixed.ScrollToFixed",i.options.postUnfixed),i.options.preAbsolute&&f.bind("preAbsolute.ScrollToFixed",i.options.preAbsolute),i.options.postAbsolute&&f.bind("postAbsolute.ScrollToFixed",i.options.postAbsolute),i.options.fixed&&f.bind("fixed.ScrollToFixed",i.options.fixed),i.options.unfixed&&f.bind("unfixed.ScrollToFixed",i.options.unfixed),i.options.spacerClass&&q.addClass(i.options.spacerClass),
f.bind("resize.ScrollToFixed",function(){q.height(f.height())}),f.bind("scroll.ScrollToFixed",function(){f.trigger("preUnfixed");k();f.trigger("unfixed");m()}),f.bind("remove.ScrollToFixed",function(){f.trigger("preUnfixed");k();f.trigger("unfixed");a(window).unbind("resize.ScrollToFixed",w);a(window).unbind("scroll.ScrollToFixed",A);f.unbind(".ScrollToFixed");i.$el.removeData("ScrollToFixed")}),w()};i.init()};a.ScrollToFixed.defaultOptions={marginTop:0,limit:0,bottom:-1,zIndex:1E3};a.fn.scrollToFixed=
function(b){return this.each(function(){new a.ScrollToFixed(this,b)})}})(jQuery);
(function(a){a.fn.lazyload=function(b){var c={threshold:0,failurelimit:0,event:"scroll",effect:"show",container:window};b&&a.extend(c,b);var g=this;"scroll"==c.event&&a(c.container).bind("scroll",function(){var b=0;g.each(function(){if(!a.abovethetop(this,c)&&!a.leftofbegin(this,c))if(!a.belowthefold(this,c)&&!a.rightoffold(this,c))a(this).trigger("appear");else if(b++>c.failurelimit)return!1});var e=a.grep(g,function(a){return!a.loaded});g=a(e)});this.each(function(){var b=this;void 0==a(b).attr("original")&&
a(b).attr("original",a(b).attr("src"));"scroll"!=c.event||void 0==a(b).attr("src")||c.placeholder==a(b).attr("src")||a.abovethetop(b,c)||a.leftofbegin(b,c)||a.belowthefold(b,c)||a.rightoffold(b,c)?(c.placeholder?a(b).attr("src",c.placeholder):a(b).removeAttr("src"),b.loaded=!1):b.loaded=!0;a(b).one("appear",function(){this.loaded||a("<img />").bind("load",function(){a(b).hide().attr("src",a(b).attr("original"))[c.effect](c.effectspeed);b.loaded=!0}).attr("src",a(b).attr("original"))});"scroll"!=c.event&&
a(b).bind(c.event,function(){b.loaded||a(b).trigger("appear")})});a(c.container).trigger(c.event);return this};a.belowthefold=function(b,c){return(void 0===c.container||c.container===window?a(window).height()+a(window).scrollTop():a(c.container).offset().top+a(c.container).height())<=a(b).offset().top-c.threshold};a.rightoffold=function(b,c){return(void 0===c.container||c.container===window?a(window).width()+a(window).scrollLeft():a(c.container).offset().left+a(c.container).width())<=a(b).offset().left-
c.threshold};a.abovethetop=function(b,c){return(void 0===c.container||c.container===window?a(window).scrollTop():a(c.container).offset().top)>=a(b).offset().top+c.threshold+a(b).height()};a.leftofbegin=function(b,c){return(void 0===c.container||c.container===window?a(window).scrollLeft():a(c.container).offset().left)>=a(b).offset().left+c.threshold+a(b).width()};a.extend(a.expr[":"],{"below-the-fold":"$.belowthefold(a, {threshold : 0, container: window})","above-the-fold":"!$.belowthefold(a, {threshold : 0, container: window})",
"right-of-fold":"$.rightoffold(a, {threshold : 0, container: window})","left-of-fold":"!$.rightoffold(a, {threshold : 0, container: window})"})})(jQuery);
(function(a,b){a(document).ready(function(){function c(){var a;if("undefined"===typeof newsfeed_type)return"";switch(newsfeed_type){case 0:a="";break;case 1:a="Featured_";break;default:a="Unknown_"}return a}function g(){a(".leftColumn").css("height","");a(".rightColumn").css("height","");var b=a(".leftColumn").outerHeight(),d=a(".rightColumn").outerHeight();b>d?(d-=a(".rightColumn").height(),a(".rightColumn").height(b-d)):(b-=a(".leftColumn").height(),a(".leftColumn").height(d-b))}function d(){a('a.j-actor-image-aggregated-follow:not(".hc-name")').hovercard(s);
a('a.actor-image-link:not(".hc-name")').hovercard(s);a('a.j-inline-player-actor:not(".hc-name")').hovercard(s);a('a.j-event-actor-name:not(".hc-name")').hovercard(s)}function e(a,b,d,e){_gaq&&_gaq.push&&(a=x+a,_gaq.push(["_trackEvent","Newsfeed",a,b,d,!!e]))}function h(a){a.siblings("img.loading").hide();a.hide()}function k(a){a.siblings("img.loading").hide()}function l(){a("#j-latest-profile-views").fadeToggle(1E3,"swing");g();a(".j-actor-image-recent-visitor").hovercard(s);e("recent_profile_widget_loaded",
void 0,void 0,!0);a("a.j-recent-visitor").hovercard(s)}function m(){a("#j-latest-viewed-content").fadeToggle(1E3,"swing");g();e("latest_content_widget_loaded",void 0,void 0,!0);a("a.j-author-latest-viewed").hovercard(s)}function t(){a("#j-featured-users").fadeToggle(1E3,"swing");g();a(".j-actor-image-featured-user").hovercard(s);e("featured_users_widget_loaded",void 0,void 0,!0);a("a.j-featured-user").hovercard(s)}function i(a,d,e){var c=a.find("ul.cardLeft");c.children("li.userImageHoverCard").children("img").attr("src",
e.information.userimage);e.information.show_follow_cta?(c.find("a.hovercard_follow_cta").show(),c.find("span.hovercard_followed_cta").hide()):(c.find("a.hovercard_follow_cta").hide(),c.find("span.hovercard_followed_cta").show());var f=a.find("ul.cardRight"),g=f.children("li.username").children("a");g.html(e.information.name);q?(c.find("a.hovercard_follow_cta").addClass("recent_visitor"),c.find("a.hovercard_follow_cta").removeClass("j-author-image"),f.children("li.username").addClass("recent_visitor"),
f.children("li.username").removeClass("j-author-link")):w?(c.find("a.hovercard_follow_cta").addClass("featured_user"),c.find("a.hovercard_follow_cta").removeClass("j-author-image"),f.children("li.username").addClass("featured_user"),f.children("li.username").removeClass("j-author-link")):A&&(c.find("a.hovercard_follow_cta").addClass("aggregated_follow"),c.find("a.hovercard_follow_cta").removeClass("j-author-image"),f.children("li.username").addClass("aggregated_follow"),f.children("li.username").removeClass("j-author-link"));
g.attr("href","/"+e.information.login+"?utm_campaign=profiletracking&utm_medium=sssite&utm_source=profile_hovercard");f.find("li.designation").html(e.information.occupation_and_organization);f.find("li.location_info").html(e.information.address);f=f.children("li.user-info").children("ul").children("li");f.children("span.followers_count").text(b.pluralize(e.information.followers,resource_file_hovercard_follow_text));f.children("span.seperator").removeClass("hide");0!==e.information.following?f.children("span.following_count").text(e.information.following+
" following"):f.children("span.following_count").text("");0===e.information.followers||0===e.information.following?f.children("span.j-hovercard-comma").hide():f.children("span.j-hovercard-comma").show();c.find("a.hovercard_follow_cta").attr("data-contactee",e.information.login);c.find("a.hovercard_follow_cta").attr("data-contactee-id",e.information.user_id);c.find("a.hovercard_follow_cta").html('<i class="iconTemp-plus-sign iconTemp-white"></i>&nbsp;Follow');c.find("span.hovarcard_followed_cta").text("Following");
d.hide();a.show()}function v(){a("#j-recommended-content").fadeToggle(1E3,"swing");g();e("recommended_content_widget_loaded",void 0,void 0,!0);a("a.j-author-recco").hovercard(s)}function f(a,b,d,c,f){slideshare_object.add_contact(b,function(b){!0===b.success?(e(d+"_successful"),c(a)):(e(d+"_Failed"),f(a))},function(){f(a)})}function p(a){a.siblings("img").hide();a.hide();var b=a.parents(".j-featured-user-visible").find(".j-follow-featured-user");0!==b.length&&r(b);a.parents("li").children("span").show();
u[a.attr("data-contactee")].information.show_follow_cta=!1}function z(a){a.siblings("img").hide()}function r(b){b.hide();b.siblings("img.follow-loading").hide();0<b.siblings("span.following").length?b.siblings("span.following").removeClass("hide"):b.siblings("span.follow-link").removeClass("hide");if(b.parent("#j-featured-users")){var d=b.parents("#j-featured-users").find(".j-featured-user-invisible")[0];(null!==d||void 0!==d)&&setTimeout(function(){a(d).addClass("j-featured-user-visible").removeClass("j-featured-user-invisible");
var e=b.parents(".j-featured-user-visible");a(e).fadeOut("fast");setTimeout(function(){a(e).html(a(d).html())},250);a(e).fadeIn("fast");setTimeout(function(){a(".j-actor-image-featured-user").hovercard(s)},250)},3E3)}var e=b.parent(".user-details").find(".j-follower-count");if(e){var c=e.html();c&&a.isNumeric(c)&&e.html(parseInt(c,10)+1+"")}}function j(a){a.siblings("img.follow-loading").hide()}a(".j-tooltip").tooltip({placement:"top",html:!0});var u={},q=!1,w=!1,A=!1,D=!1,E=!1,F=!1,G=!1,C=!0;a(window).focus(function(){C=
!0});a(window).blur(function(){C=!1});var y=0;window.location.pathname.match("newsfeed")&&window.setInterval(function(){C&&600>y?(y+=20,e("time_on_page",y+"",void 0,!0)):600<=y&&window.clearInterval(2E4)},2E4);var H=function(){window.location.pathname.match("newsfeed")&&(people_event_count&&e("Impressions","People",people_event_count),slideshows_event_count&&e("Impressions","Slideshows",slideshows_event_count),top_ss_count&&e("Impressions","Featured_Slideshows",top_ss_count))},K=setInterval(function(){window.location.pathname.match("newsfeed")&&
(G&&F&&E&&D)&&(a("#j-sticky-widgets").scrollToFixed({marginTop:10,limit:function(){return a("footer").offset().top-650}}),clearInterval(K))},1E3),x=c();g();if("undefined"!==typeof is_newsfeed_page){_gaq.push(["_setAccount","UA-2330466-1"]);_gaq.push(["_setDomainName",".slideshare.net"]);_gaq.push(["_addIgnoredRef","slideshare.net"]);_gaq.push(["_trackPageview"]);_gaq.push(["_trackEvent","quick_upload_experiment","newsfeed_pageload"]);""===x?e("page_load",slideshows_event_count+people_event_count+
"",void 0,!0):e("page_load",void 0,void 0,!0);0<a(".li-connect-box").children(".j-li-box").length&&e("li_connect_load",void 0,void 0,!0);var n=".follow-cta-event";"Featured_"==x&&(n+="-featured");0<a(n).length&&e("follow_cta_load",void 0,void 0,!0)}""===x&&("undefined"!==typeof newsfeed_from_followers_feed&&newsfeed_from_followers_feed)&&e("converted_newsfeed_page_load");var B=!1;a("a.j-commentEntry").live("click",function(){e("comment_anchor");var b=a(this).parents("ul.newsFeedCTA").siblings("div.commentInput");
b.is(":visible")?b.fadeOut():(b.fadeIn(),b.find("textarea").focus())});a(".j-PostCommentButton").live("click",function(){var b=a(this),d=b.prev().val();if(a(this).hasClass("loggedout"))slideshare_object.userActionsStore.saveComment(d,b.attr("data-ss-id"));else{b.hide();b.siblings("img.loading").show();""!==d&&e("Post_Comment_Button");var c=b.attr("data-stripped-title"),f=b.attr("data-author-id");a.ajax({url:"/comment/create",type:"POST",data:{slide_title:c,user_id:f,"comment[text]":d},success:function(){e("Post_Comment_Button_Successful");
b.siblings("img.loading").hide();b.show();var c=b.parents("div.commentInput");c.hide();var f=b.parents("div.j-cta-hide");0===a(f).length&&(f=b.parents("li.j-newsfeed-event"));var f=f.find(".comments-wrapper"),g=a("div.j-comment-wrapper").find("li").clone();g.find("span.comment-text").append(a("<div/>").html(b.prev().val().replace(/\r?\n/g,"<br/>")));g.prependTo(f);g.show();slideshare_object.user.is_opengraph_user&&(f={name:"comment",message:d,ppt_url:b.attr("data-ppt-url")},slideshare_object.post_activity_to_facebook(f,
function(a){log(a)}));c.show();c.find("textarea").val("")},error:function(){b.siblings("img").hide();b.show()}})}});a(".j-hovercard-follow").live("click",function(){if(a(this).hasClass("loggedout"))slideshare_object.userActionsStore.saveFollow(a(this).attr("data-contactee"));else{var b=a(this);b.siblings("img").show();if("Follow"===b.text().strip()){var d=b.attr("data-contactee");f(b,d,"Follow_aggregated",p,z)}}});a(".j-hovercard-follow.recent_visitor").live("click",function(){e("recent_visitors_hc_follow_anchor_clicked")});
a(".j-hovercard-follow.j-author-image").live("click",function(){e("hc_follow_anchor_clicked")});a("#slideshow_pptfile").live("click",function(){e("upload_widget_clicked")});a(".j-hovercard-follow.featured_user").live("click",function(){e("featured_user_hc_follow_anchor_clicked")});a(".j-hovercard-follow.aggregated_follow").live("click",function(){e("aggregated_hc_follow_anchor_clicked")});a(".j-googleplay-cta").on("click",function(b){b.preventDefault();e("newsfeed_ssapp_android");window.location.href=
a(this).attr("href")});a(".j-favoriteNewsfeed").click(function(){var b=a(this);if(a(this).hasClass("loggedout"))slideshare_object.userActionsStore.saveLike(b.attr("data-ssid"),!1);else{var d;d=b.hasClass("j-favorited")?"unfavorite":"favorite";0!==b.parents(".featured-agg-wrapper").length&&(d="top_"+d);e(d+"_anchor_clicked")}});a(".j-followNewsfeed").live("click",function(){var b=a(this);b.siblings("img").show();$contactee=b.attr("data-contactee");e("follow_link_clicked");f(b,$contactee,"Follow",h,
k)});a(".actor-image-link").live("click",function(){e("actor_image_clicked")});a(".actor-image-link-aggregated").live("click",function(){e("aggregated_actor_image_clicked")});a(".j-slideshow-thumbnail-recent-content").live("click",function(){e("recent_content_slideshow_open")});a(".j-li-box").live("click",function(){e("linkedin_connect_clicked")});a(".j-slideshow-thumbnail-recommended-content").live("click",function(){e("recommended_content_slideshow_open")});a(".actor-link").live("click",function(){e("actor_link_clicked")});
a("li.username.j-author-link").live("click",function(){e("hovercard_actor_link_clicked")});a("li.username.recent_visitor").live("click",function(){e("recent_visitor_hovercard_actor_link_clicked")});a(".j-actor-image-recent-visitor, a.user-details.j-recent-visitor").live("click",function(){e("recent_profile_visitors_clicked")});a("li.username.featured_user").live("click",function(){e("featured_user_hovercard_actor_link_clicked")});a("li.username.aggregated_follow").live("click",function(){e("aggregated_follow_hovercard_actor_link_clicked")});
a(".j-inline-player-actor").live("click",function(){e("inline_player_actor_link_clicked")});a(".j-actor-image-featured-user, a.user-details.j-featured-user").live("click",function(){e("featured_user_link_clicked")});a(".slideshow-link").live("click",function(){e("slideshow_link_clicked")});a(".user-followed-link").live("click",function(){e("user_followed_link_clicked")});getUrlVar("nf_redirect",location.href)&&slideshare_object.ga("Newsfeed","redirect_from_login",void 0,void 0,!0);getUrlVar("redirect",
location.href)&&slideshare_object.ga("Newsfeed","redirect_from_homepage",void 0,void 0,!0);getUrlVar("from_whotofollow",location.href)&&slideshare_object.ga("Newsfeed","redirect_from_who_to_follow",void 0,void 0,!0);var s={detailsHTML:a(".hover-wrapper").html(),width:350,delay:200,onHoverIn:function(){var b=a(this).find("a"),d=a(this).find(".j-cardbaloon2"),e=a(this).find(".cardBaloonLoading"),c=a(this).find("a").attr("data-hovercard"),c=c.replace("/","");u[c]?i(d,e,u[c],b):a.ajax({url:"/newsfeed/profile_hovercard",
type:"GET",dataType:"json",data:{login:c},beforeSend:function(){d.hide();e.show()},success:function(a){i(d,e,a,b);u[c]=a},error:function(){e.hide()}})}};a(window).load(function(){d();var b=a("ul.rightpanel");slideshare_object.favorites_status_update(b);slideshare_object.bind_favorites(b);if("undefined"!==typeof is_newsfeed_page){var e=[{wrapper:"#j-recommended-content",url:"/newsfeed/get_recommended_content",success_callback:v},{wrapper:"#j-featured-users",url:"/newsfeed/get_featured_users",success_callback:t},
{wrapper:"#j-latest-profile-views",url:"/newsfeed/get_latest_profile_visitors",success_callback:l},{wrapper:"#j-latest-viewed-content",url:"/newsfeed/get_latest_viewed_content",success_callback:m}];a(e).each(function(b){var d=e[b].url,c=e[b].wrapper,f=e[b].success_callback,b=window.location.pathname.split("/")[1],g=a(c)[0],h={};h.login=b;getUrlVar("auth")&&!slideshare_object.user.loggedin&&(h.auth=getUrlVar("auth"));a.ajax({url:d,type:"GET",dataType:"json",async:!0,data:h,success:function(b){if(!0===
b.success){switch(c){case "#j-latest-profile-views":D=!0;break;case "#j-latest-viewed-content":E=!0;break;case "#j-featured-users":F=!0;break;case "#j-recommended-content":G=!0}0<b.number&&(g.innerHTML=b.html,f(b),a(".j-tooltip").tooltip({placement:"top",html:!0}))}},error:function(){}})});""===x&&H()}});""===c()&&"undefined"!==typeof is_newsfeed_page&&a(window).scroll(function(){var b=a("ul.rightpanel").children(":last-child"),c=a("div.footerWrapper"),f=a(window).scrollTop(),h=f+a(window).height(),
c=c.offset().top,f=c+b.offset().top>=f&&c<=h+200&&c>=h-50,h=a(window).scrollTop()==a(document).height()-a(window).height();if((f||h)&&!1===B)if(B=!0,e("Infinite_Newsfeed"),!b.hasClass("no-updates")){b.show();g();f=window.location.pathname.split("/");slideshare_object.user.su&&getUrlVar("experiment");var f=f[1],i=a("ul.rightpaneltemp"),f={last_event_at:last_event_at,login:f,slideshows_excluded:slideshows_excluded};getUrlVar("auth",location.href)&&(f.auth=getUrlVar("auth",location.href));a.ajax({url:"/newsfeed/infinite_scroll",
type:"POST",dataType:"json",async:!0,data:f,success:function(c){b.hide();!1===c.success&&!b.hasClass("no-updates")?(e("Infinite_Newsfeed_No_Updates"),a(c.html).appendTo(i)):(e("Infinite_Newsfeed_More_Updates"),a(c.html).appendTo(i),H());B=!1;slideshare_object.favorites_status_update(i);slideshare_object.bind_favorites(i);g();a(".j-tooltip").tooltip({placement:"top"});a("ul.rightpanel").append(i.html());d();i.empty()},error:function(){b.hide();e("Infinite_Newsfeed_failed");B=!1}})}});a("a.j-modal-player").live("click",
function(b){var d=a(this);if(d.hasClass("j-top-event"))e("top_slideshow_image_clicked");else if(d.hasClass("j-slideshow-outbound"))e("inline_slideshow_player_link_click");else{var c=d.parents(".j-newsfeed-event");(c.hasClass("inline-player-single-event")||c.hasClass("aggregated-event-user"))&&e("slideshow_image_clicked")}b.preventDefault();b=a(".j-ss-player");c=d.parents().find("input#embed-url").val();d=d.attr("data-ppt-id");b.html(c);slideshare_object.modal_player.init(d,"Newsfeed")});var I=function(a){return"<iframe src='http://www.slideshare.net/slideshow/embed_code/"+
a+"?rel=0&hostedIn=slideshare' width='611' height='503' frameborder='1' marginwidth='0' marginheight='0' scrolling='no' style='border:none;margin-bottom:0;border-right:1px solid #ddd;'allowfullscreen='true'></iframe>"},n=slideshare_object.userActionsStore.getStoredAction();if(null!==n&&slideshare_object.user.loggedin)if(n.action_data.load_modal)a(".j-ss-player").html(I(n.action_data.ss_id)),slideshare_object.modal_player.init(n.action_data.ss_id,"Newsfeed",n);else if("ss_like"===n.action_type)a("a[data-ss-id="+
n.action_data.ss_id+"]").click();else if("ss_follow"===n.action_type)slideshare_object.add_contact(n.action_data.contactee,function(){});else{var J=a(".j-PostCommentButton[data-ss-id="+n.action_data.ss_id+"]");a(J).siblings("textarea").text(n.action_data.comment);a(J).click()}else getUrlVar("ss",location.href)&&setTimeout(function(){var b=getUrlVar("ss",location.href);a(".j-ss-player").html(I(b));slideshare_object.modal_player.init(b,"Newsfeed")},1E3);a(".j-follow-recent-visitor, .j-follow-featured-user, .j-follow-latest-content").live("click",
function(){var b=a(this).attr("data-contactee"),d="featured_user_widget_follow";a(this).hasClass("j-follow-recent-visitor")?(d="recent_visitor_widget_follow",e("recent_visitor_widget_follow_anchor_clicked")):a(this).hasClass("j-follow-latest-content")?(d="latest_content_widget_follow",e("latest_content_widget_follow_anchor_clicked")):a(this).hasClass("j-follow-featured-user")&&e("featured_user_widget_follow_anchor_clicked");a(this).siblings("img.follow-loading").show();f(a(this),b,d,r,j)});a(".j-follow-modal").live("click",
function(){if(a(this).hasClass("loggedout"))slideshare_object.userActionsStore.saveFollow(a(this).data("contactee")),a("#follow_box .close").click(),initiate_login_modal(a(".j-bulk-follow").data("href"),a(".j-bulk-follow").data("target"));else{var b=a(this).attr("data-contactee");e("modal_follow_clicked");a(this).siblings("img.follow-loading").show();f(a(this),b,"modal_follow",r,j)}});a(".j-follow-aggregated, .j-follow-single").live("click",function(){if(a(this).hasClass("loggedout"))slideshare_object.userActionsStore.saveFollow(a(this).attr("data-contactee"));
else{var b=a(this).attr("data-contactee"),d="follow_inline";a(this).hasClass("j-option1")?d+="_aggregated_1":a(this).hasClass("j-option2")&&(d+="_aggregated_2");e(d+"_clicked");a(this).siblings("img.follow-loading").show();f(a(this),b,d,r,j)}});a(".j-bulk-follow").live("click",function(){var b=a("#j-bulk-follow-ids").val(),d=a(".modal-body"),c=window.location.pathname.split("/")[1];a(this).hasClass("loggedout")?(slideshare_object.userActionsStore.saveBulkFollow(b),a("#follow_box .close").click(),
initiate_login_modal(a(this).data("href"),a(this).data("target"))):(e("bulk_follow_clicked",void 0,b.split(",").length),a.ajax({url:"/newsfeed/modal_bulk_follow",type:"POST",data:{bulk_ids:b,login:c},success:function(b){a(".bulk-follow-loader").hide();b.success&&(a(".j-bulk-follow").attr("disabled",!0),d.find(".j-follow-modal").each(function(){a(this).hide();a(this).siblings(".follow-link").show()}))},error:function(){a(".bulk-follow-loader").hide()},beforeSend:function(){a(".bulk-follow-loader").show()}}))});
a(".j-more-followers").live("click",function(){e("aggregated_modal_open");var b=a(this).parents(".feedInfo").find(".j-followers-list").val(),d=window.location.pathname.split("/")[1],c=a("#follow_box"),f=a(this).parents(".feedInfo").find(".userAction .actor-link").html(),b={followers:b,actor_name:f,login:d};getUrlVar("auth",location.href)&&!slideshare_object.user.loggedin&&(b.auth=getUrlVar("auth",location.href));a.ajax({url:"/newsfeed/get_followers_modalbox",type:"POST",data:b,success:function(b){b.success?
(c.html(b.html),a(".j-tooltip").tooltip({placement:"top"})):c.html("<div class='alert alert-error margin20'>Oops, something went wrong, Please try again!</div>")},error:function(){c.html("<div class='alert alert-error margin20'>Oops, something went wrong, Please try again!</div>")},beforeSend:function(){a(".j-modal-loader h3").html(f+" started following");c.html(a(".j-modal-loader").html())}})});a(".j-follow-cta").live("click",function(){a(this).hasClass("j-experiment")?e("follow_cta_clicked_experiment"):
e("follow_cta_clicked")});a(".ccode-box").click(function(){cookie("culture_code_seen",!0,{path:"/",expires:1E3})})})})(jQuery,slideshare_object);var set_window_location=function(a){try{window.location.href=a}catch(b){window._gaq=_gaq||[],_gaq.push(["_trackEvent","Profiles","Orchestra: Iframe communication error in accordion",window.location.href])}};
(function(a,b){var c={register_listeners:function(){b("a.j-follow").live("click",function(a){var c=b(this).attr("data-contactee");if(slideshare_object.user.loggedin)return b(a.target).parent().next().show(),b(a.target).parent().hide(),slideshare_object.ga("Profiles","slidespace_orchestra_follow",b(this).attr("data-ga")),slideshare_object.add_contact(c,function(c){b(a.target).parent().next().hide();c.success?(slideshare_object.ga("Profiles","slidespace_orchestra_follow_successful",b(this).attr("data-ga")),
b(a.target).parent().prev().show()):(b(a.target).parent().show(),slideshare_object.ga("Profiles","slidespace_orchestra_follow_failure",b(this).attr("data-ga")))}),!1;slideshare_object.addAfterLoginEvent({event:"follow",data:{contactee:c}})});b("a.j-unfollow").live("click",function(a){var c,g="You are following "+slideshare_object.owner.return_name;c="Following";g=b("<div>").text(g||"Are you sure you want to proceed?").html();dialog='<div id="dialog" style="display:none;" title="'+c+'"><p><span class="ui-icon ui-icon-info" style="float:left; margin:0 7px 20px 0;"></span>'+
g+"</p></div>";b("body").append(dialog);b("#dialog").dialog({bgiframe:!0,resizable:!1,height:140,modal:!1,overlay:{backgroundColor:"#000",opacity:0.5},closeOnEscape:!0,dialogClass:"confirm",close:function(){b(this).dialog("destroy")},buttons:{Unfollow:function(){b(this).dialog("close");slideshare_object.ga("Profiles","slidespace_orchestra_unfollow");b(a.target).parent().next().next().show();b(a.target).parent().hide();slideshare_object.delete_contact(slideshare_object.owner.id,function(){b(a.target).parent().next().next().hide();
b(a.target).parent().next().show()},function(){b(a.target).parent().next().next().hide();b(a.target).parent().show()})},Close:function(){b(this).dialog("close")}}});return!1});b(".j-tooltip").tooltip()},block_interaction:function(){var a=function(a,d){b("#myModal").modal({backdrop:"static"});b("#myModalLabel").html(a);b(".modal-body p").html(d);b("#myModal").modal("show").find(".modal-footer").show()};b(".j-block-user").live("click",function(){b(".modal-footer .j-yes").attr("id","block");a("Block User",
"Are you sure you want to block the user?")});b(".j-unblock-user").live("click",function(){b(".modal-footer .j-yes").attr("id","unblock");a("Unblock User","Are you sure you want to unblock the user?")});b(".modal-footer .j-yes").live("click",function(){var a=b(".modal-body p"),d=this.id,c=b(this).attr("data-id");a.html("<img src='//public.slidesharecdn.com/images/indicator.gif' height='5' width='21'/>");b(".modal-footer").slideUp("slow");b.post("//"+document.location.host+"/block/"+d,{blocked_id:c},
function(c){c.success?(a.html("The user has been "+d+"ed."),"block"==d?b(".j-block-user").text("Unblock User").removeClass().addClass("j-unblock-user"):b(".j-unblock-user").text("Block User").removeClass().addClass("j-block-user"),setTimeout(function(){myModal.modal("hide")},3E3)):a.html("Oops! Something went wrong. Please try again later.")})})},private_message_interaction:function(){b(".j-private_message").fancybox({hideOnContentClick:!1,enableEscapeButton:!0,centerOnScroll:!1,dontShowFancyTitle:!0,
overlayOpacity:0.85,padding:0,margin:0,overlayColor:"#000",onStart:function(){b(".dropdown-toggle").dropdown("toggle")}});b("#fancy_div #composeForm").live("click",function(a){var c={};c.recipient=slideshare_object.owner.login;c.subject=b("#fancy_div #subject").val();c.message=b("#fancy_div #message").val();b(a.target).next().show();b(a.target).hide();b.ajax({url:"/message/send_message",data:c,type:"POST",dataType:"json",cache:!1,success:function(c){b(a.target).next().hide();b(a.target).show();c.success?
(b("#fancy_div #compose").hide(),b("#fancy_div #j-compose_success").show(),setTimeout("$.fn.fancybox.close()",4E3)):(b("#fancy_div .j-pvtMessage #error").parent().show(),null!==c.error&&b("#fancy_div .j-pvtMessage #error").html(c.error))}})})},adjust_height:function(){b(".sidebar").css("height","");b(".mainContent").css("height","");var a=b(".sidebar").outerHeight(),c=b(".mainContent").outerHeight();a>c?(c-=b(".mainContent").height(),b(".mainContent").height(a-c)):(a-=b(".sidebar").height(),b(".sidebar").height(c-
a))}},g={cache:{},tags_interaction:function(){b("#showMoreTags,#showLessTags").click(function(a){"showMoreTags"==a.target.id?(b("#tagsLess").hide().siblings("#tagsMore").show(),b("#search_uploaded_tags").show()):(b("#tagsMore").hide().siblings("#tagsLess").show(),b("#search_uploaded_tags").hide());"undefined"!==typeof c&&c.adjust_height();return!1})},removeFavorites:function(){var a=b(g.cache.removeFavoriteElement.target),c=a.parents("li"),h=a.attr("href").split("#")[1],k=slideshare_object.owner.id;
delete g.cache.removeFavoriteElement;b(".j-fav_count").html(parseInt(b(".j-fav_count").html(),10)-1);a.next().show();b.post("/favorite/delete",{slideshow_id:h,user_id:k},function(){var a=c.siblings();c.hide(1E3,function(){c.remove();b.each(a,function(a,c){var d=b(c);d.removeClass("last");0===(a+1)%4&&d.addClass("last")})})});return!1},confirmRemoveFavorites:function(b){g.cache.removeFavoriteElement=b;a.confirm("Confirm","Are you sure want to remove this from favorites ?",g.removeFavorites)&&delete g.cache.removeFavoriteElement},
updateFavoriteTags:function(a){a={user_id:slideshare_object.owner.id,slideshow_id:g.cache.editTag.attr("href").split("#")[1],"favorite[tag_text]":a};b.post("/favorite/update",a,function(){window.location.reload()})},editFavoriteTags:function(c){var c=b(c.target),e=c.parent().parent().children(".tags"),h="";g.cache.editTag=c;b.each(e,function(a,c){h+=b(c).html()+","});h=h.slice(0,-1);a.prompt("Please update the tags","Tags :",h,g.updateFavoriteTags);c=b("#prompt_value");a.tagTextBoxInteraction(c);
return!1},searchUploadedTags:function(a){a=b(a.target).val();""!==a?b("#tagsMore span").hide().filter("[id*="+a+"]").show():b("#tagsMore span").show()},pixel_tracker:function(){try{a.pixel_tracker&&b("body").append(a.pixel_tracker)}catch(c){window._gaq=_gaq||[],_gaq.push(["_trackEvent","Pixel tracker errors",c.toString(),window.location.href])}},fb_app_tracker:function(){var a=getUrlVar("fb_source");if(getUrlVar("code")||a)a?slideshare_object.ga("fb_opengraph","profile_visit",a):slideshare_object.ga("fb_opengraph",
"profile_visit","no_fb_source")},showToolTip:function(){jQuery(".getToolTip").hover(function(){jQuery(this).siblings("span.tooltip").show()},function(){jQuery(this).siblings("span.tooltip").hide()})},subscriptionCta:function(){window._gaq=_gaq||[];_gaq.push(["_trackEvent","subscription","subscriptionCtaProfile"])},proCtaTracker:function(){b(".j-ad_remove").click(function(){window._gaq=_gaq||[];_gaq.push(["_trackEvent","Profiles","remove_ad_cta_clicked"])})},search_interaction:function(){b("#search_uploaded_tags").keyup(g.searchUploadedTags);
b("#search_uploaded_tags").focus(function(b){b=b.target;"search"===b.value&&(b.value="");a.ga("Profiles","slidespace_search_favorite_tags")});b("#search_uploaded_tags").blur(function(a){a=a.target;""===a.value&&(a.value="search")});b("#search_content").focus(function(){if((!g.cache.search_content||g.cache.search_content==this.value)&&this.value.match("Search content from "))g.cache.search_content=this.value,this.value="";a.ga("Profiles","slidespace_search_content")}).blur(function(){this.value=""===
this.value?g.cache.search_content:this.value})},async_thumbnails_load:function(){b([{selector:".thumbnailFollowGrid>li a>span>img.nickname",options:{effect:"fadeIn",placeholder:slideshowPlaceholder}}]).each(function(a,c){b(c.selector).lazyload(c.options)})}};b(document).ready(function(){g.tags_interaction();b(".remove_favorited").click(g.confirmRemoveFavorites);b(".edit_tags").click(g.editFavoriteTags);g.search_interaction();g.pixel_tracker();g.fb_app_tracker();0<b(".upgrade_subscription").length&&
(g.showToolTip(),g.subscriptionCta());g.proCtaTracker();"undefined"===typeof innerpage&&g.async_thumbnails_load();c.register_listeners();c.block_interaction();c.private_message_interaction();window.setTimeout(c.adjust_height,1E3*("undefined"===typeof innerpage?5:0));b("form#j-flag-user").live("ajax:beforeSend",function(){b("#ban_user_email_progress_"+(slideshare_object.owner.id+"")).show()});b("form#j-flag-user").live("ajax:complete",function(a,c){var g=slideshare_object.owner.id+"";200===c.status?
b("#ban_user_email_"+g).html(c.responseText):b("#ban_user_email_progress_"+g).hide()});b("a#j-warning-email").live("ajax:beforeSend",function(){b("#ban_user_email_progress_"+(slideshare_object.owner.id+"")).show()});b("a#j-warning-email").live("ajax:complete",function(){b("#ban_user_email_progress_"+(slideshare_object.owner.id+"")).hide()});slideshare_object.action_from_email_check()})})(slideshare_object,jQuery);
(function(){var a={},b=null,c=null,g=document.title,d=null,e=null,h={},k={width:7,height:9,font:"10px arial",colour:"#ffffff",background:"#F03D25",fallback:!0},l,m=navigator.userAgent.toLowerCase();l=function(a){return-1!==m.indexOf(a)};l("chrome");var t=l("chrome")||l("safari"),i=l("safari")&&!l("chrome"),v=l("mozilla")&&!l("chrome")&&!l("safari"),f=function(){e||(e=document.createElement("canvas"),e.width=16,e.height=16);return e},p=function(){if(f().getContext){for(var a=f().toDataURL(),b=document.getElementsByTagName("link"),
c=document.getElementsByTagName("head")[0],d=0,e=b.length;d<e;d++)"icon"===b[d].getAttribute("rel")&&c.removeChild(b[d]);b=document.createElement("link");b.type="image/x-icon";b.rel="icon";b.href=a;document.getElementsByTagName("head")[0].appendChild(b)}};a.setOptions=function(a){h={};for(var b in k)h[b]=a[b]?a[b]:k[b];return this};a.setImage=function(a){b=a;p();return this};a.setBubble=function(a){if(isNaN(a))window.console&&window.console.log("Bubble must be a number");else{var e=a;if(!f().getContext||
i||"force"===h.fallback)h.fallback&&(document.title=0<e?"("+e+") "+g:g);else{var j=f().getContext("2d"),e=e||0;d=new Image;d.crossOrigin="anonymous";d.onload=function(){j.clearRect(0,0,16,16);j.drawImage(d,0,0,d.width,d.height,0,0,16,16);if(0<e){var a=e,b=h.width+6*((a+"").length-1),c=16-b,f=16-h.height;j.font=(t?"bold ":"")+h.font;j.fillStyle=h.background;j.strokeStyle=h.background;j.lineWidth=1;j.fillRect(c,f,b-1,h.height);j.beginPath();j.moveTo(c-0.5,f+1);j.lineTo(c-0.5,15);j.stroke();j.beginPath();
j.moveTo(15.5,f+1);j.lineTo(15.5,15);j.stroke();j.beginPath();j.strokeStyle="rgba(0,0,0,0.3)";j.moveTo(c,16);j.lineTo(15,16);j.stroke();j.fillStyle=h.colour;j.textAlign="right";j.textBaseline="top";j.fillText(a,15,v?7:6)}p()};a=d;if(!c||!b){var k;b:{k=document.getElementsByTagName("link");for(var l=0,m=k.length;l<m;l++)if((k[l].getAttribute("rel")||"").match(/\bicon\b/)){k=k[l];break b}k=!1}c=b=k?k.getAttribute("href"):"/favicon.ico"}a.src=b}return this}};a.reset=function(){a.setImage(c)};a.setOptions(k);
window.Tinycon=a})();
slideshare_object.userActionsStore={saveAction:function(a,b){sessionStorage?(sessionStorage.setItem("ss_actiontype",a),sessionStorage.setItem("ss_actiondata",JSON.stringify(b))):(window.cookie("ss_actiontype",a),window.cookie("ss_actiondata",JSON.stringify(b)))},getStoredAction:function(){var a=null,b=null;sessionStorage?(a=sessionStorage.getItem("ss_actiontype"),b=sessionStorage.getItem("ss_actiondata"),null!==a&&null!==b&&(sessionStorage.removeItem("ss_actiontype"),sessionStorage.removeItem("ss_actiondata"))):(a=
window.cookie("ss_actiontype"),b=window.cookie("ss_actiondata"),null!==a&&null!==b&&(window.cookie="ss_actiontype=; expires=Thu, 01 Jan 1970 00:00:01 GMT;",window.cookie="ss_actiondata=; expires=Thu, 01 Jan 1970 00:00:01 GMT;"));return null!==a&&null!==b?{action_type:a,action_data:JSON.parse(b)}:null},saveLike:function(a,b){this.saveAction("ss_like",{ss_id:a,load_modal:"undefined"!==typeof b?b:!1})},saveFollow:function(a,b,c){this.saveAction("ss_follow",{contactee:a,load_modal:"undefined"!==typeof b?
b:!1,slideshow_id:"undefined"!==typeof b?c:null})},saveBulkFollow:function(a){this.saveAction("ss_follow",{contactee:a,load_modal:!1,slideshow_id:null})},saveComment:function(a,b,c){this.saveAction("ss_comment",{ss_id:b,comment:a,load_modal:"undefined"!==typeof c?c:!1})}};
